#!/bin/bash

rbenv() {
  unset -f rbenv
  . rbenvload &> /dev/null
  rbenv "$@"
}

nvm() {
  unset -f nvm
  . nvmload &> /dev/null
  nvm "$@"
}

ruby() {
  unset -f ruby
  rbenv &> /dev/null
  ruby "$@"
}


gem() {
  unset -f gem
  rbenv &> /dev/null
  gem "$@"
}

node() {
  unset -f node
  nvm &> /dev/null
  node "$@"
}

npx() {
  unset -f npx
  nvm &> /dev/null
  npx "$@"
}

npm() {
  unset -f npm
  nvm &> /dev/null
  npm "$@"
}

yarn() {
  unset -f yarn
  nvm &> /dev/null
  yarn "$@"
}

pnpm() {
  unset -f pnpm
  nvm &> /dev/null
  pnpm "$@"
}
